### PR TITLE
Optimize the wasm memory allocation mode

### PR DESCRIPTION
**Pull request by L-jasmine**
About [fix: load wasi_nn plugin](https://github.com/libsql/libsql/commit/3f17a103f087c3ed18c4f0512fbc81d46cae350d):
---
On WasmEdge 0.11.2 .
When load `wasi_nn` plugin, we need call `WasmEdge_ConfigureAddHostRegistration(ConfCxt, WasmEdge_HostRegistration_WasiNN);`.
But On WasmEdge 0.12.0+ , It is not needed.

About [fix: pass TEXT & BLOB by malloc](https://github.com/libsql/libsql/commit/69e92d963fe6dfde3ccf361dfef97a20dab892a8)
---
In the old approach to alloc wasm memory (by `memory.grow`) , when allocating large memory internally in wasm, it's possible for data to be overwritten, resulting in bugs.

In the new approach, by calling the `malloc` function exported from within the wasm, a memory address that does not conflict with the wasm can be obtained to store data.

But not all wasm modules export the `malloc` function. For Rust and C/C++, you can achieve this by specifying ld-flags at compile time. 

* C/C++ export `malloc` use [wasi-sdk](https://github.com/WebAssembly/wasi-sdk)
```
export WASI_SDK_PATH=`pwd`/wasi-sdk-${WASI_VERSION_FULL}
CC="${WASI_SDK_PATH}/bin/clang --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot"
$CC foo.c -o foo.wasm  -Wl,--export=malloc
```

* Rust export `malloc`  like [this](https://github.com/second-state/wasmedge_plugin_rust_sdk/blob/3144ca866256359a0bfe8b08f1ce98d5004bf86f/examples/wasm/call_memory_access/.cargo/config.toml#L7). 

* For wasm modules where the compilation process is not controllable, I will provide a tool to locate the malloc function and generate a new wasm module. This tool works for 90% of the wasm modules generated by Rust and C/C++.

However, I still recommend WebAssembly developers to manually export a malloc function.

### CODE REVIEW

**Comment by juntao** [comment]
The way I understand it -- this is an issue with bindgen. We would like to pass a big chunk of data into the Wasm function (eg a blob field). The bindgen library needs to be able to handle this from both host and Wasm sides. 

So, we are proposing to make changes both inside the libsql WasmEdge engine and the `libsql_bindgen` library. BTW, `wasm_bindgen` and `wasmedge_bindgen` libraries already do this.

I believe once those changes are made, developers simply needs to recompile a new Wasm bytecode file from their source code. The new Wasm file will work with both WasmEdge and wasmtime in libsql.

@L-jasmine Please also propose a PR to `libsql_bindgen` for the above. 

@psarna Please let us know what you think!

**Comment by psarna** [comment]
Hi, indeed, a proper solution for passing parameters is indeed a memory allocator, not a naive memory.grow. Thanks for bringing the issue up and contributing a proper fix!

I see that the test suite needs to be updated to provide `libsql_malloc` as well, but otherwise the change looks great.

**Comment by L-jasmine** [comment]
> Hi, indeed, a proper solution for passing parameters is indeed a memory allocator, not a naive memory.grow. Thanks for bringing the issue up and contributing a proper fix!
> 
> I see that the test suite needs to be updated to provide `libsql_malloc` as well, but otherwise the change looks great.

Thank you, I couldn't find the source code for the Wasm tests. If you could provide them, I can make an update. Also, the Wasmtime part needs to be updated as well.

**Comment by psarna** [comment]
Yeah, I created the wasmtime issue here: #146 . Tests are here: https://github.com/libsql/libsql/tree/main/test/rust_suite/src . https://github.com/libsql/libsql/blob/main/test/rust_suite/src/user_defined_functions_src.rs contains the WAT source code for the tested functions, so I suppose it's enough to just add a simple export of `libsql_malloc` in there. Or, regenerate them with patched `libsql-bindgen` - I already released 0.3.0 with your `libsql_malloc` patch applied: https://crates.io/crates/libsql-bindgen

**Comment by L-jasmine** [comment]
Why don't we use 0i32 to represent LIBSQL_NULL?

**Comment by psarna** [comment]
> Okay, but for these tests, I can't generate libsql_malloc from the WAT because their malloc function is either missing or has already been inlined. So, I need to recompile their original code. Alternatively, can I write a new WAT myself?

Sure, feel free to regenerate a totally new WAT

**Comment by psarna** [comment]
> Why don't we use 0i32 to represent LIBSQL_NULL?

That's a great idea, feel free to create an issue and/or post a change! For backward compatibility, the old encoding for NULL parameters should also stay just in case

**Comment by psarna** [comment]
> > Why don't we use 0i32 to represent LIBSQL_NULL?
> 
> That's a great idea, feel free to create an issue and/or post a change! For backward compatibility, the old encoding for NULL parameters should also stay just in case

@L-jasmine oh wait, isn't 0 pointer in Wasm technically a perfectly legal pointer that points to memory[0]? In which case we'd need to also specify in bindgen that address 0 is reserved

**Comment by L-jasmine** [comment]
Don't worry, in c/c++ and rust, due to programming language history, they don't use the 0 pointer, but instead use it to denote null. You can also verify this in the table. All tables[0] generated by them (c++ rust) will not be used because table[0] is reserved as null to represent function pointers.
```wat
(table $0 5 5 funcref)
(elem (i32.const 1) $__stdio_close $__stdout_write $__stdio_seek $__stdio_write)
```
table elem is start from 1, but not 0;

**Comment by L-jasmine** [comment]
I noticed that the WAT files I generate are quite large (around 200K+), and I'm concerned that including them in `user_defined_functions_src.rs` would result in a very large file. Can you please share your approach for generating compact wasm files? It would be really helpful.

**Comment by psarna** [comment]
> I noticed that the WAT files I generate are quite large (around 200K+), and I'm concerned that including them in `user_defined_functions_src.rs` would result in a very large file. Can you please share your approach for generating compact wasm files? It would be really helpful.

@L-jasmine hmm I don't remember exactly, but I think I just used our https://bindgen.libsql.org, which is an instance of https://github.com/libsql/libsql_generate and its `generate.sh` script. That, plus I removed a couple of unused exports by hand at the end

**Comment by psarna** [comment]
And for very simple functions, I remember that clang actually produces much less bloated binaries, especially with -Os flag. So perhaps I hand-coded the functions in C to match our abi... I wish I remembered for 100%. Tommorow I'll go over my files and maybe I'll find a trace of how I generated all the cases.

Alternatively, the tests could be rewritten to just always generate the functions with libsql-bindgen via build.rs, but that's a larger change

**Comment by L-jasmine** [comment]
I have completed the modifications for Wasmtime. Can I also make the Wasmtime backend support WASI?

**Comment by psarna** [comment]
Sure, feel free, WASI makes sense and allows for quite a few more Rust crates to work with libsql-bindgen. Thanks so much!

**Comment by psarna** [comment]
Fantastic! Let me just deploy the new bindgen on https://bindgen.libsql.org and retest that it works properly, and the series is good to go. Thank you so much for the contribution!

**Comment by psarna** [comment]
Done, works. Thanks again!

**Pull request merged**
