### PR TITLE
Drop .fossil-settings

### PR DESCRIPTION
**Pull request by penberg**
We don't use Fossil nor plan to, so drop the config.

### CODE REVIEW

**Comment by penberg** [comment]
@psarna What do you think about removing some of these things that we will never use? Will it make merging back from SQLite unnecessary hard?

**Comment by psarna** [comment]
Let's wait until the first backport of SQLite stuff (which we can try next week and start a regular schedule), and then decide

**Comment by penberg** [comment]
@psarna Makes sense, will leave this pull request open until we make a decision.

**Comment by penberg** [comment]
@psarna What do you want to do with this? Merge or close?

**Comment by psarna** [comment]
Perhaps left it in limbo for a while longer? Mostly because it would be interesting to recursively test libsql by testing fossil itself, because it uses SQLite as its blob store. And perhaps it would be easier with fossil settings in place

**Comment by psarna** [comment]
rationale: those config files were last edited in 2017 according to `git blame`, and they can be restored very easily should anyone need them (which isn't going to happen)

**Pull request merged**
