### PR TITLE
Build liblibsql.{so,a} and install wasm bindings

### PR DESCRIPTION
**Pull request by honzasp**
Introduce `liblibsql.so` and `liblibsql.a` to accomodate users who want to link specifically to libSQL, and not sqlite3. This PR also changes how the building of the wasm bindings is organized in the configure script and in the Makefile, though the result is still highly suboptimal, because the build system was never designed to support building multiple inter-dependent libraries in a mixture of languages.

One way to make the build system more robust would be to create libtool file `libsql_wasm.la` for the `libsql_wasm` library compiled from Rust. This is left as future work.

The Makefile now includes target `liblibsql_install`, which installs only `liblibsql` and not `libsqlite3`. This allows users to use libSQL while keeping the original SQLite intact.

### CODE REVIEW

**Comment by psarna** [comment]
@honzasp thanks, looks good! CI most likely failed just because the dynamic library was renamed to `liblibsql_wasm`. The workflow definition needs to be updated as well: https://github.com/libsql/libsql/blob/1d24f5a2bda50d97136f00e949b7abc2e424a3ca/.github/workflows/maketestwasm.yml#L24

**Comment by honzasp** [comment]
@psarna Could you please approve running the workflow again?

**Comment by psarna** [comment]
@honzasp you're a collaborator in the repository, could you try pushing another fix to see if CI would launch automatically this time?

**Comment by honzasp** [comment]
@psarna It still needs approval from you

**Comment by honzasp** [comment]
But once this PR is merged, I will no longer be a first-time contributor so the approval may not then be necessary.

**Comment by psarna** [comment]
@honzasp just restarted the build, since it's not clear what failed and why. By the way, since you decided to change the library name from libwblibsql (with which I'm fine), please `git grep` every occurrence of it and change accordingly. One place that's important for me is the `tool/generate-artifacts.sh` script, which I use for generating release artifacts.

**Comment by psarna** [comment]
ah, it's "cargo is not found" again

**Comment by honzasp** [comment]
Uhhhh, I have no idea what's going on. I assume that cargo must have worked previously, why am I getting these errors?! I will look into it, but I really don't like this messing with CI :(

**Comment by honzasp** [comment]
I fixed the script and use dtolnay/rust-toolchain instead of running rustup manually. Piotr, could you please approve running the pipeline again? :) @psarna

**Comment by psarna** [comment]
Will do! Thanks. This PR is slowly becoming a piority since I'd like to release libSQL 0.2.0 early next week, and that's a good opportunity to rename the library that holds our Wasm bindings.

**Comment by psarna** [comment]
@honzasp hm, it says `/bin/sh: 1: cargo: not found` - perhaps the script that runs and downloads `cargo` doesn't put it in `$PATH` and it has to be done manually?

**Comment by psarna** [comment]
on the other hand, https://github.com/dtolnay/rust-toolchain 's README suggests that it should work out of the box... weird

**Comment by psarna** [comment]
ah, maybe `/bin/sh` is the key? Perhaps the build chain from SQLite uses it, and dtolnay/rust-toolchain only sets the path correctly in `.bashrc` or something?

I still can't really fathom why it stopped working in this PR only, other PRs also run cargo in their CIand work seamlessly

**Comment by psarna** [comment]
@honzasp turns out that for some unbeknownst reason I'm allowed to push to your fork of libsql :sweat_smile: probably because this branch is a pull request. In any case, I'll take liberty of some weekend debugging to get this one working!

**Comment by psarna** [comment]
@honzasp ok, figured it out, it's because of `sudo make liblibsql_install`, root does not see cargo. I'll fix it today and then we can proceed. Thanks!

**Comment by psarna** [comment]
Btw, this whole ordeal will become irrelevant once we rewrite the whole codebase in Rust 😇

**Comment by honzasp** [comment]
Thank you so much for tackling this, Piotr! :)

**Pull request merged**
