### PR TITLE
chore: Add OpenSSF scoreboard to the README

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**
The scoreboard checks a project's level of professionalism and combines a lot of metrics including the [OpenSSF best practices score](https://bestpractices.coreinfrastructure.org/en).

### CODE REVIEW

**Comment by psarna** [comment]
Note that for the badge to work, best practices poll must be filled first: https://bestpractices.coreinfrastructure.org/en/projects/6725 . I skimmed through it and ticked some boxes, but it's not complete yet. Thanks for suggesting this badge!

**Comment by Abdur-rahmaanJ** [comment]
@psarna No need to complete all, the badge will still work.

It is very tough to get a perfect score and much work for a decent score, but, i think that the project already has a lot done.

CI/CD tests 

static code analysis maybe we'll need!

**Comment by psarna** [comment]
The links from this PR still resolve to an "invalid repo path" badge, so perhaps coreinfrastructure.org needs to catch up with matching the project number and its github link?

**Comment by Abdur-rahmaanJ** [comment]
Ah i mean you need to create and save the project even if it is empty on the best practices site.

**Comment by penberg** [comment]
The rendered badge is showing "invalid repo path". Closing this as inactive.

**Pull request closed without merging**
