### PR TITLE
sync cr-sqlite to ext/crr

### PR DESCRIPTION
**Pull request by tantaman**
#147 

copy `cr-sqlite` extension code as-is to `ext/crr`

build & test

https://app.warp.dev/block/FWDFdN9HSg4jaHayk3EwBo
https://app.warp.dev/block/lseqHcw4cpmyqWMBsyexs5

Next steps:
- remove `src/sqlite/shell.c,sqlite3.c,sqlite3.h,sqlite3ext.h` and use the files present in `libsql`
- Integrate w/ autotools
- integrate tests with your CI
- remove reliance on `commit_hook`
- draft new `create crr` syntax
- fuzzing?

Note: the `package.json` and other `js` files are for distribution of this extension on npm.

There are also a number of integration tests in Python and TypeScript (using https://github.com/dubzzz/fast-check) not included here. I'm thinking of the best way to include those.

### CODE REVIEW

**Comment by psarna** [comment]
thanks @tantaman! How can I verify that everything works, manually? I tried going to `crr/rs/core` and running `cargo build` from there, but it fails to find a `deps/sqlite3ext.h` when running `sqlite-rs-embedded/sqlite3_capi/build.rs`. I saw that the original repo has a Makefile one can use to build the extension, but it's not part of this PR

**Comment by tantaman** [comment]
hmm. Let me double check that I got everything.

**Comment by tantaman** [comment]
`make loadable` in the `crr` directory should do the trick.

```
> pwd
libsql/ext/crr
> make loadable
> ls dist
crsqlite.dylib			sqlite3-extra.c			test.dSYM
libcrsql_bundle-loadable.a	test
```

`make test` is also a target although it doesn't run the Rust tests.

Rust tests are in `ext/crr/rs/integration-check`

```
cargo test
```

I'm in the process of porting all the C code to Rust but I'll update the `make test` target to run both `C` and `Rust` tests.

**Comment by tantaman** [comment]
Hah, yeah. The .gitignore file in the libsql root excludes `Makefile`

https://github.com/libsql/libsql/blob/7ecf22a1a61e13655427b576c3a2a7c9f1ef485b/.gitignore#L3-L5

```
> git check-ignore crr/Makefile -v
.gitignore:4:Makefile	crr/Makefile
```

**Comment by psarna** [comment]
Ah, right. Feel free to also amend the .gitignore file so it explicitly ignores all the Makefiles that make sense, while preserving e.g. ones from ext/

**Comment by psarna** [comment]
thanks, I'll go over the warnings and fix, and meanwhile let's just wait for CI to finish and we can merge the initial PR!

**Comment by psarna** [comment]
@tantaman which flags did you use to ./configure libsql before running `make loadable`? I'm trying to reproduce the redefinition warnings from your first warp link but they didn't happen in any configurations I tried

**Pull request merged**
