### PR TITLE
Use `read_exact` instead of `read_exact_at`

### PR DESCRIPTION
**Pull request by avinassh**
I am trying to use libsql API library and aiming to cross compile my app across OS. Currently it uses a *nix OS specific import and can't be used on Windows. This patch tries to fix that. 

- We are using `read_exact_at` but at offset zero, so it is same as `read_exact`
- Earlier, it was reading twice into buffer. Any particular reason for that? I changed it to read it once

### CODE REVIEW

**Comment by avinassh** [comment]
This PR currently breaks, but #324 fixes the import error

**Comment by penberg** [comment]
Hey @avinassh! The change looks good to me, but I also wonder why we're reading twice. Let's try to get @MarinPostma or @psarna to have a look at this before merging.

**Comment by MarinPostma** [comment]
Looks good. Idk why we were reading twice, likely a mistake

**Comment by MarinPostma** [comment]
Do we want to bother with making sqld compile on windows? Just asking

**Comment by penberg** [comment]
@MarinPostma Sure, I think it's good to keep stuff running on Windows when possible.

**Pull request merged**
